version: 2.1

workflows:
  sample:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout

      - run:
          name: Run tests
          command: python PasswordGeneratorTests.py
